name: Lint and Fix

on: [push, pull_request]

jobs:
  lint-and-fix:
    name: Lint and fix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          xo: true
          auto_fix: true